### PR TITLE
Check that input files exist before opening editor

### LINKED ISSUE #19: The program should check that the input files does exist
TSIA I think!
```
$ renamer i-do-not-exist

..... [open editor, make changes] .....

The following replacements were found:

i-do-not-exist -> i-do-not-exist-foo

Execute these renames? yes
Error: No such file or directory (os error 2)
```

### PR DESCRIPTION
**Pull request by 1117x**
Closes #19

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -216,6 +216,21 @@ fn check_for_existing_files(replacements: &Vec<Rename>) -> anyhow::Result<()> {
     Ok(())
 }
 
+fn check_input_files(input_files: &Vec<String>) -> anyhow::Result<()> {
+    let nonexisting_files : Vec<_> = input_files.iter().filter(|input_file| !Path::new(input_file).exists()).collect();
+
+    if !nonexisting_files.is_empty() {
+        println!("The following input files do not exist:");
+        for file in nonexisting_files {
+            println!("{}", Colour::Green.paint(file));
```
Comment (bew) [inline src/main.rs:225]: What about red or yellow to better show there is a problem?

Comment (1117x) [reply src/main.rs]: Yes, you are right. I used the same color for the files printed when checking for existing files. Maybe these should also be in red/yellow?

**Comment by marcusbuffett** [comment]
Looks great! Sorry for the slowness here, merging now :+1:
